service: mongo-be
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
